### PR TITLE
Link badge to PyPI rather than static image

### PR DESCRIPTION
**Pull request by hugovk**
# Before

Links to https://camo.githubusercontent.com/b83044c95d5d1a2c1390bf6f3e9ec5acb0b4dcbd/68747470733a2f2f696d672e736869656c64732e696f2f707970692f707976657273696f6e732f696e666c6563742e737667

# After

Links to https://pypi.org/project/inflect/

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks for this. The badge derives from the [jaraco/skeleton project](/jaraco/skeleton), so if it should be changed there.

However, I'm not sure it should be changed. That's just one more link that has to be updated for every project that uses it, and there's already a badge that links to PyPI. If I were to add that to jaraco/skeleton, it would need to be updated for the hundreds of downstream packages that use the template.

It's weird that there's a link at all. I think I'd prefer if the badge simply did not link to anything.

Oddly, the [docs seem to imply](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image) that an image without a `:target:` directive would not link to anything, but clearly it does.

I think I'd prefer to just keep things consistent and let the link be broken. What do you think?

**Comment by hugovk** [comment]
I'd definitely change it from linking to the image, that has very little value.

Linking to PyPI is by far the most common thing in Python projects. Doing something else is inconsistent with the community as a whole, and could be a bit confusing.

If it can be changed to a static image that links nowhere, that would be probably be okay. But it's normal for badges to link to somewhere.

But it sounds like skeleton needs some sort of templating, to be able to insert the project name, so "one more link" isn't a problem. I don't know how that would fit in with the skeleton model, though.

---

Or, as there's already one PyPI link for the version badge, can we DRY it?

For example:

```rst
.. image:: https://img.shields.io/pypi/v/inflect.svg
   :target: `PyPI link`_

.. image:: https://img.shields.io/pypi/pyversions/inflect.svg
   :target: `PyPI link`_

.. _PyPI link: https://pypi.org/project/inflect
```

**Comment by jaraco** [comment]
That's great. Feel free to do that here and I can port it upstream, or submit it upstream and I'll merge it in here.

**Comment by hugovk** [comment]
I've done both :) https://github.com/jaraco/skeleton/pull/13

**Pull request merged**
