### PR TITLE
Fix python_requires

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.0 and 3.1 are not supported.

Also add 3.7 to classifiers.

### CODE REVIEW

**Comment by hugovk** [comment]
@jaraco How does this look?

**Comment by jaraco** [comment]
This looks good to me. Thanks for bringing it to my attention. Separately, we should probably drop support for Python 3.3 and maybe 3.4 also soon.

**Comment by jaraco** [comment]
Hmm. Looks like the work was superseded by #45.

**Comment by hugovk** [comment]
Oh, so it was! Thanks!

**Pull request closed without merging**
