### PR TITLE
Allow special case dictionaries to match on lowercase final word

### PR DESCRIPTION
**Pull request by jayaddison**
While inflecting some ingredient-related content, I'd noticed that although the word `olives` is currently handled correctly by `singular_noun`, `black olives` is not:

```pycon
>>> import inflect
>>> inflect.__version__
'4.0.0'
>>> e = inflect.engine()
>>> e.singular_noun('olives')
'olive'
>>> e.singular_noun('black olives')
'black olife'
```

In the `inflect` code, the handling of single-word `olives` is performed by a [special case](https://github.com/jazzband/inflect/blob/407dfa7e170a562012f37e9bd65c3b50cd3da0cb/inflect.py#L1438) which overrides the [default logic](https://github.com/jazzband/inflect/blob/407dfa7e170a562012f37e9bd65c3b50cd3da0cb/inflect.py#L3210-L3211) for items ending `...ves`.

This is one of a number of special cases gated by boolean conditions of the form `if lowerword in <map>:`, which fail if `lowerword` doesn't exactly match with a key in the `<map>`.

Switching these conditions to use `lowerwordlast` instead of `lowerword` results in additional matches for multi-word phrases without negatively impacting any existing test cases.

It's arguably not 'perfect' since multi-word phrases may have challenging plurality rules (like the situations handled by the [compound](https://github.com/jazzband/inflect/blob/407dfa7e170a562012f37e9bd65c3b50cd3da0cb/inflect.py#L2518) logic, but hopefully it's a reasonably safe improvement.

This also resolves https://github.com/jazzband/inflect/issues/30 which falls into a similar special case relating to `...ies` tokens.

### CODE REVIEW

**Comment by jayaddison** [comment]
@hugovk @jaraco Does this seem like a reasonable change?  Glad to make any modifications / changes to the approach here; just let me know once you have time to take a look.

**Comment by jayaddison** [comment]
Thanks for the review!

I could apply underscores to the variable name in this branch, or in a follow-up PR?  (there are a few similar/related variables such as `wordlast` which might benefit from that treatment at the same time)

**Comment by hugovk** [comment]
If there's not too many, I'd put them here.

**Comment by jayaddison** [comment]
@hugovk Great; the number of related variable names seems manageable - I've applied camel-casing of those here too.

**Comment by jayaddison** [comment]
@jaraco Any additional review/comments I could factor in here?

**Comment by jayaddison** [comment]
Hi @hugovk @jaraco - is there anything I could do to nudge this (and my other PR) towards merging?  I'd be really glad to set jazzband/inflect as my upstream dependency; very happy to apply any further changes to make sure they're acceptable to the project & others.

**Comment by jaraco** [comment]
I'm a little uneasy with this change, which is I why I didn't simply merge it. Let me see if I can articulate why.

# Complication (1)

Focusing on [the first commit](https://github.com/jazzband/inflect/pull/95/commits/873a24ed69ac6092a883bf95b07f8156acb83789#diff-f050578c8ba7c79cee9ecda099818b2cR3160-R3165) to isolate the primary change here.

At first blush, this seems like a potentially reasonable improvement, but when I look at the code, this one simple change interacts with the code in a number of different complex ways. It touches the code at more than a dozen places, including some copy/paste code.

I'd feel much better about this change if it were encapsulated as a function or class.

To be fair, the code is already pretty complicated and messy and could use some improved structure to more easily accept changes like this.

# Complication (2)

This implementation while adding `lower_word_last` continues to use `lower_word` in slices adding to the number of variables at play through the logic. Is there a version of this change where `lower_word_last` is used unconditionally?

# Testing

It seems unlikely to me that the two test cases that were supplied are sufficient to adequately cover the changes herein. The tests should at least cover each of the uses added.

# Correctness

Most importantly, I'm concerned that this change adds support for a much broader set of uses. Instead of supporting inflection for words, the project would not be supporting inflection for arbitrarily large phrases. For example, one could pass `"black and white olives"` or all of Shakespeare's Hamlet and presumably get an answer:

```
inflect.engine.plural(hamlet)
'offs'
```

Is that really what this library should be doing?

And on the converse, this library while supporting inflecting the last word, will fail to support inflecting other words in the phrase. For example, how would it handle 'cookies remaining' or 'attorney general'? Oh, interesting--I just learned that it does support the latter:

```
>>> inflect.engine().plural('attorney general')
'attorneys general'
```

I have no idea how it does that.

# Other thoughts

> If there's not too many, I'd put them here.

Unfortunately, this change has made it harder to review. I would have recommended doing that in a separate PR. Thankfully, you didn't rebase, so I was able to use the original commit to review the core change.

I did push the change for snake-casing to master, and resolved the conflict with the [improve-special-case-matching branch](https://github.com/jazzband/inflect/tree/improve-special-case-matching). I'd have pushed that to your branch but for permissions. Feel free to pull in that commit to resolve the conflicts.

----

Overall, the change seems reasonable, and I'm tempted to just merge it and iterate on it.

Let me know your thoughts on my concerns while I reflect a bit more on it.

**Comment by hugovk** [comment]
> Most importantly, I'm concerned that this change adds support for a much broader set of uses. Instead of supporting inflection for words, the project would not be supporting inflection for arbitrarily large phrases. For example, one could pass `"black and white olives"` or all of Shakespeare's Hamlet and presumably get an answer:
> 
> ```
> inflect.engine.plural(hamlet)
> 'offs'
> ```
> 
> Is that really what this library should be doing?

Specifically on this point, the library follows the [junk-in, junk-out principle](https://github.com/jazzband/inflect/search?q=garbage+OR+junk&unscoped_q=garbage+OR+junk&type=Issues), which could cover inflecting all of Hamlet.

**Comment by jayaddison** [comment]
Thanks @jaraco - I appreciate the time taken to inspect and review the changes here.

# Complication (1)

Although there is indeed a relocation of variable declarations, this is intended to be a light-touch change; to ensure that `lower_word_last` is defined consistently, `word_split` and `word_last` need to be declared beforehand, and so the cluster of variables is moved to a single declaration location.  It shouldn't affect anything else about the intent, scope or contents of the variables themselves.

I'd be open to considering wrapping the change in a function, although the styling of the code as-is seems to prefer one-time variable declarations (i.e. static work performed one-time-only to generate a variable, and then multiple subsequent uses) and so I'd aimed for consistency over encapsulation - which might not be perfect but hopefully would simplify future refactoring.

# Complication (2)

Agreed, it's not ideal that `lower_word_last` closely resembles the `lower_word` variable - it would be nice if both could be derived from a common root.

There are cases such as the handling of pronouns ([ref](https://github.com/jazzband/inflect/blob/b70ab7ac8e2e98c23c25ee42224a79d9419cd3cb/inflect.py#L2577)) which rely on breaking apart the `lower_word` based on whitespace in order to produce the correct results, and `lower_word_last` isn't a drop-in replacement in those cases since it lacks enough context.

# Testing

Let me see what I can do here - I do think the large dictionary tests are helpful in catching potential regressions, but I can probably add a few more tests to add more coverage and gain a bit more assurance.

# Correctness

I'm relatively confident in the correctness of the change, although this could also be helped by further tests.  The `inflect` library as-is does handle some multi-word inputs - including pronouns as referenced earlier in this comment, and -- although it's maybe not the most readable --  compound phrases like `attorneys general` as you found (handled [here](https://github.com/jazzband/inflect/blob/b70ab7ac8e2e98c23c25ee42224a79d9419cd3cb/inflect.py#L2521-L2523)).

As per the garbage-in-garbage-out principle, multi-noun phrases (`x and y`) are hopefully out of scope; it may be arguable that `<adj> noun` is getting near the boundary with garbage-in, but if it can be handled gracefully without affecting other use cases, I'd hope it might be a nice improvement.

# Other

Thanks for pulling in the snake-casing changes; I've pulled those in here too (after one false start - hopefully this can be squashed down at merge-time).

There's usually an option in GitHub to provide maintainers edit access to PRs, but unfortunately I don't see that for this one - I don't suppose there are any branch restrictions in `jazzband/inflect` ([settings link](https://github.com/jazzband/inflect/settings/branches))?  That's the only thing from the GitHub [docs](https://help.github.com/en/github/administering-a-repository/about-branch-restrictions) that stands out as a possible cause there, but I could be missing something.

Thanks again for the help and review!

**Comment by jayaddison** [comment]
Regarding additional test coverage:

Since I couldn't see many straightforward ways to define the edges/boundary conditions of the behaviour, and since the dictionary tests should indicate correctness, I've instead taken the approach of trying to ensure that existing test coverage and assertions hold true under the change.

What I have found so far is that `test_plequal` - which tests the plural-equality between two noun phrases - does not consider multi-word phrases to be of the same plurality, even if the underlying noun is the same.  This is something that it can handle correctly for single-word cases.

That seems like a nice thing to fix since it could lead to unexpected results and debugging for someone else in future if unresolved.

**Comment by jayaddison** [comment]
The reason `plequal` did not return consistent results was that one of the internal methods it uses ([code ref](https://github.com/jazzband/inflect/blob/b70ab7ac8e2e98c23c25ee42224a79d9419cd3cb/inflect.py#L2420-L2439)) was operating on full input texts - i.e. *not* using the `lower_word_last` - when performing a regular expression match against a set of stems.

Since that would have duplicated code (i.e. `word1_last = ..., word2_last = ...`) to fix in-place, I took the suggestion about wrapping all this in a class, which performs word tokenization during the constructor (retaining the same calculate-once, read-many access pattern).

This does bump up the diff quite significantly, and perhaps my variable naming might not be the best; it's an approach we can discuss though, glad to hear what you think.

**Comment by jayaddison** [comment]
@jaraco A small bump on the change of approach here; a class is now instantiated per-word to wrap the generation of word tokens (replacing repeated assignment of `lower_word_last` and related variables).  Let me know what you reckon.

**Comment by jaraco** [comment]
Released as v4.1.0.

**Comment by jayaddison** [comment]
Brilliant, thank you @jaraco !

**Pull request merged**
